### ISSUE TITLE
submit to conda-forge

### ISSUE THREAD

**Issue by njzjz** [openbabel/conda-openbabel#2]
hi,

Do you mind if I submit this recipe to [conda-forge](https://github.com/conda-forge/staged-recipes)? This will greatly help dependencies of other software.

**Comment by ghutchis** [comment]
No, no problem at all - @baoilleach - are you okay with this?

**Comment by baoilleach** [comment]
Go for it. Just spoke to @mcs07 too.

**Comment by njzjz** [comment]
The recipe has been submitted to conda-forge. However, it doesn't work on macOS. (openbabel/openbabel#1932)
