### ISSUE TITLE
Pybel missing library

### ISSUE THREAD

**Issue by mskblackbelt** [openbabel/conda-openbabel#9]
I tried installing OpenBabel via `conda install -c conda-forge openbabel`, and it seemed to succeed. I'm able to find the `obabel` binary and all of the tests in `meta.yaml` run just fine. However, when I try to run `import pybel` in python (either a Jupyter notebook or the REPL), I get 

    ModuleNotFoundError: No module named 'pybel'

It looks like the python bindings aren't built or just not linked to the local library. Is there a quick fix I can do for this?

**Comment by mcs07** [comment]
Use `from openbabel import pybel` since v3

**Comment by mskblackbelt** [comment]
Got it, thank you. The version of `cclib` on conda-forge is still out of date, that was the source of my confusion.
